### ISSUE TITLE
can someone give a basic tutorial how to use this?

### ISSUE THREAD

**Issue by ghost** [commandRobot/gridfinity-rhino3d#1]
I am a long time rhino user but not experienced in grasshopper at all. 
Can anyone post a few screenshots or basic uses for this to the main code page
Would be awesome to just place the parameters in rhino on a toolbar so we can set them as needed but I can't figure out how to add the brep/bake buttons into rhino itself, only the parameters. Not sure how to add buttons as the method for adding the parameters isn't working for those "breps" or bake option.

Would also like to put whether i want an X _or_ Y divider if I did not want both. Possibly even a slider where to place the divider for say if i want a 1x5 divided by two to get a divider down the middle of the 1x section or vice versa.

![image](https://user-images.githubusercontent.com/7325420/221299348-e0dfd921-bc36-41ea-9f43-7afedeb61330.png)

**Comment by nawzaysfinah** [comment]
> I am a long time rhino user but not experienced in grasshopper at all. Can anyone post a few screenshots or basic uses for this to the main code page Would be awesome to just place the parameters in rhino on a toolbar so we can set them as needed but I can't figure out how to add the brep/bake buttons into rhino itself, only the parameters. Not sure how to add buttons as the method for adding the parameters isn't working for those "breps" or bake option.
> 
> Would also like to put whether i want an X _or_ Y divider if I did not want both. Possibly even a slider where to place the divider for say if i want a 1x5 divided by two to get a divider down the middle of the 1x section or vice versa.
> 
> ![image](https://user-images.githubusercontent.com/7325420/221299348-e0dfd921-bc36-41ea-9f43-7afedeb61330.png)

you're right a readme is long overdue. 
working on one now, will let you know

**Comment by nawzaysfinah** [comment]
> I am a long time rhino user but not experienced in grasshopper at all. Can anyone post a few screenshots or basic uses for this to the main code page Would be awesome to just place the parameters in rhino on a toolbar so we can set them as needed but I can't figure out how to add the brep/bake buttons into rhino itself, only the parameters. Not sure how to add buttons as the method for adding the parameters isn't working for those "breps" or bake option.
> 
> Would also like to put whether i want an X _or_ Y divider if I did not want both. Possibly even a slider where to place the divider for say if i want a 1x5 divided by two to get a divider down the middle of the 1x section or vice versa.
> 
> ![image](https://user-images.githubusercontent.com/7325420/221299348-e0dfd921-bc36-41ea-9f43-7afedeb61330.png)

Thank you for your suggestions.

Things done:
1. [README](https://github.com/commandRobot/gridfinity-rhino3d/blob/main/README.md) with basic instructions on using Grasshopper and the Hops component to use the [gridfinity.ghx](https://github.com/commandRobot/gridfinity-rhino3d/blob/main/gridfinity.ghx) file.  
2. New options for toggling on & off X & Y separators (as suggested)
3. Attempted to add a bake directly within the gridfinity.ghx file, but for some reason does not work when it is a hop. Hence, added a [template GH file](https://github.com/commandRobot/gridfinity-rhino3d/blob/main/gridfinity_HopsDefault.gh) with the gridfinity hop & a bake component attached

Things not done:
1. Divider control within each gridfinity cell. Currently dividers are only between cells. A quick alternative is that one you bake the geometries, you can easily drag them and snap them to place as preferred with simple manipulation in Rhino.

Hope this helps! Thanks!
